name: wuchuheng_isolate_subject
description: A starting point for Dart libraries or applications.
version: 0.0.1
homepage: https://www.example.com

environment:
  sdk: '>=2.18.0-271.4.beta <3.0.0'

dependencies:
  wuchuheng_hooks: ^0.0.3

dev_dependencies:
  json_serializable: ^6.3.1
  json_annotation: ^4.6.0
  wuchuheng_logger: ^0.0.1
  lints: ^2.0.0
  test: ^1.16.0
  build_runner: ^2.0.0
