on:
  push:
    tags-ignore:
      - '**'
    branches:
      - '**'
name: Test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1.3

      - name: Install dependencies
        run: dart pub get

      - name: Testing
        run: dart test