name: test-isolate-channel
on: [push, workflow_dispatch]
jobs:
  drive:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Flutter
        uses: subosito/flutter-action@v1.3.2
      - name: Install app dependencies
        run: flutter pub get
      - name: Test app
        run: flutter test --coverage